import retriveDoc from "../services/retriveDoc.js";
import geminiService from "../services/geminiService.js";

/*
  RagProcess

  Flow:
  User Question
        ↓
  Retrieve Relevant Chunks
        ↓
  Build Context
        ↓
  Send Context + Question to Gemini
        ↓
  Return Final Answer
*/

async function RagProcess(question, selectedfiles, userId) {
  try {
    // Retrieve relevant chunks from selected files
    const context = await retriveDoc(
      question,
      selectedfiles,
      userId
    );

    // Create RAG prompt
    const prompt = `
Context:
${context}

Question:
${question}

Answer using the provided context.
If the answer is not found in the context, say so.
`;

    const response = await geminiService(prompt);

    // Handle Gemini API failures
    if (!response.success) {
      console.error("Gemini Error:", response.message);

      return `Error: ${response.message}`;
    }

    // Extract generated answer safely
    const answer =
      response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!answer) {
      return "No response generated by Gemini.";
    }

    return answer;
  } catch (error) {
    console.error("RAG PROCESS ERROR:", error);

    return "An unexpected error occurred while processing your request.";
  }
}

export default RagProcess;